### ISSUE TITLE
Remove www?

### ISSUE THREAD

**Issue by theofidry** [phpmetrics/website#3]
Would it be possible to remove the `www` subdomain? I guess it's a question of personal taste, but I always felt like `www` was completely unnecessary and got in the way.

**Comment by joubertredrat** [comment]
I agree with this, because `http://www.phpmetrics.org/` open site, but `http://phpmetrics.org/` make nothing.

Then I think that is good to make `http://phpmetrics.org/` redirect to `http://www.phpmetrics.org/` or make site open on `http://phpmetrics.org/` only.

**Comment by UFOMelkor** [comment]
Related: phpmetrics/PhpMetrics#289

**Comment by niconoe-** [comment]
From @SenseException:
> On phpmetrics 2.2.0, links to the PHPMetrics homepage, in console and in the generated report, are http://phpmetrics.org.
> Currently http://phpmetrics.org fails, but http://www.phpmetrics.org works fine. I suggest to enable http://phpmetrics.org too instead of making a PR to fix all the domain names in the project.
